var mongoose = require('mongoose');


var atcoSchema = new mongoose.Schema({
        "Nº Convencional": String,
        "Acordão": String,
        "Processo": String,
        "Relator": String,
        "Descritores": [String],
        "Nº do Documento": String,
        "Data do Acordão": String,
        "Espécie": String,
        "Requerente": String,
        "Requerido": String,
        "Votação": String,
        "Privacidade": String,
        "Normas Apreciadas": String,
        "Normas Julgadas Inconst.": String,
        "Área Temática": String,
        "Área Temática 2": String,
        "Decisão": String,
        "Sumário": String,
        "Texto Integral": String,
        "url": String,
        "tribunal": String,
        "_id": String,
        "Volume dos Acordãos do T.C.": String,
        "Constituição": String,
        "Legislação Nacional": String,
        "Nº do Diário da República": String,
        "Série do Diário da República": String,
        "Data do Diário da República": String,
        "Página do Diário da República": String,
        "Nº do Boletim do M.J.": String,
        "Página do Boletim do M.J.": String,
        "Jurisprudência Constitucional": String,
        "Normas Suscitadas": String,
        "Declaração de Voto": String,
        "Voto Vencido": String,
        "Indicações Eventuais": String,
        "Normas Declaradas Inconst.": String,
        "Página do Volume": String,
        "Outras Publicações": String,
        "Legislação Comunitária": String,
        "Referência a Pareceres": String,
        "Referências Internacionais": String,
        "Outra Jurisprudência": String,
        "Jurisprudência Internacional": String,
        "Jurisprudência Estrangeira": String,
        "Legislação Estrangeira": String
});


module.exports = new mongoose.model('atco',atcoSchema,'atco');