var mongoose = require('mongoose');


var databaseSchema = new mongoose.Schema({
        "Nº Convencional": String,
        "Acordão": String,
        "Processo": String,
        "Relator": String,
        "Descritores": [String],
        "Nº Documento": String,
        "Data do Acordão": String,
        "Espécie": String,
        "Requerente": String,
        "Requerido": String,
        "Votação": String,
        "Privacidade": String,
        "Normas Apreciadas": String,
        "Normas Julgadas Inconst.": String,
        "Área Temática": String,
        "Área Temática 2": String,
        "Decisão": String,
        "Sumário": String,
        "Texto Integral": String,
        "url": String,
        "tribunal": String,
        "Recorrente": String,
        "Recorrido 1": String,
        "Recorrido 2": String,
        "Tribunal 1ª instância": String,
        "Juízo ou Secção": String,
        "Tipo de Ação": String,
        "Tipo de Contrato": String,
        "Autor": String,
        "Réu": String,
        "Data da Decisão": String,
        "Texto das Cláusulas Abusivas": String,
        "Recursos": String,
        "Tribunal": String,
        "Data de Entrada": String,
        "Meio Processual": String,
        "Secção": String,
        "Contencioso": String,
        "Data": String,
        "Nº Processo/TAF": String,
        "Sub-Secção": String,
        "Magistrado": String,
        "Peça Processual": String,
        "Tema": String,
        "Parecer Ministério Publico": String,
        "Tribunal Recurso": String,
        "Legislação Nacional": String,
        "Indicações Eventuais": String,
        "Texto Parcial": String,
        "Reclamações": String,
        "_id": String
});


module.exports = new mongoose.model('database', databaseSchema);